import argparse
from pathlib import Path
import yaml

TEMPLATE_MEMBRANE = """package main

// Auto-generated by lam scaffold

type Membrane struct {
    Ingress string
    Egress string
    Guards []string
}

var membrane = Membrane{
    Ingress: "%s",
    Egress: "%s",
    Guards: []string{%s},
}
"""

TEMPLATE_NUCLEUS = """package main

// Auto-generated by lam scaffold

type Nucleus struct {
    Kind        string
    Version     string
    EthicsLevel string
    Intents     []string
    Energy      string
    Memory      string
}

var nucleus = Nucleus{
    Kind: "%s",
    Version: "%s",
    EthicsLevel: "%s",
    Intents: []string{%s},
    Energy: "%s",
    Memory: "%s",
}
"""

TEMPLATE_GUARDIAN = """package guardian

// Auto-generated by lam scaffold

type Threshold struct {
    Warn string
    Crit string
}

type Guardian struct {
    Heartbeat   Threshold
    AnomalyRate struct{Warn float64; Crit float64}
}

var GuardianSpec = Guardian{
    Heartbeat: Threshold{Warn: "%s", Crit: "%s"},
    AnomalyRate: struct{Warn float64; Crit float64}{Warn: %s, Crit: %s},
}
"""
def scaffold(yaml_path: Path, out_dir: Path) -> None:
    """Generate Go boilerplate from a YAML cell specification."""
    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    cell = data.get("cell", {})
    mem = cell.get("membrane", {})
    guardian = cell.get("guardian", {}).get("thresholds", {})

    guards = ", ".join([f'"{g}"' for g in mem.get("guards", [])])
    mem_code = TEMPLATE_MEMBRANE % (
        mem.get("ingress", ""),
        mem.get("egress", ""),
        guards,
    )

    intents = ", ".join([f'"{i}"' for i in cell.get("intents", [])])
    nuc_code = TEMPLATE_NUCLEUS % (
        cell.get("kind", ""),
        cell.get("version", ""),
        cell.get("ethics_level", ""),
        intents,
        cell.get("resources", {}).get("energy", ""),
        cell.get("resources", {}).get("memory", ""),
    )

    hb = guardian.get("heartbeat", {})
    ar = guardian.get("anomalyRate", {})
    guard_code = TEMPLATE_GUARDIAN % (
        hb.get("warn", ""),
        hb.get("crit", ""),
        ar.get("warn", ""),
        ar.get("crit", ""),
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "membrane.go").write_text(mem_code, encoding="utf-8")
    (out_dir / "nucleus.go").write_text(nuc_code, encoding="utf-8")
    gdir = out_dir / "guardian"
    gdir.mkdir(parents=True, exist_ok=True)
    (gdir / "guardian.go").write_text(guard_code, encoding="utf-8")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="lam")
    subparsers = parser.add_subparsers(dest="command")

    sc_parser = subparsers.add_parser(
        "scaffold", help="Generate Go boilerplate from YAML spec"
    )
    sc_parser.add_argument("yaml", type=Path)
    sc_parser.add_argument("--out", type=Path, default=Path("."))

    args = parser.parse_args(argv)

    if args.command == "scaffold":
        scaffold(args.yaml, args.out)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
